AssetManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from authentication.forms import UserPasswordChangeForm, UserPasswordResetForm, UserPasswordResetRequestForm
from authentication.decorators import unauthenticated_user


urlpatterns = [
    path('secret/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('vendors/', include('vendors.urls', namespace='vendors')),
    path('products/', include('products.urls', namespace='products')),
    path('admin/', include('dashboard.urls', namespace='dashboard')),
    path('upload/', include('upload.urls', namespace='upload')),
    path('recycle-bin/', include('recycle_bin.urls', namespace='recycle_bin')),
    path('assets/', include('assets.urls', namespace='assets')),
    path('roles/', include('roles.urls', namespace='roles')),
    path('support/', include('support.urls', namespace='support')),
    path('users/', include('users.urls', namespace='users')),
    path('notifications/', include('notifications.urls', namespace='notifications')),

    # django smart select urls
    path('chaining/', include('smart_selects.urls')),

    # Password Change Views
    path('change-password/', auth_views.PasswordChangeView.as_view(form_class=UserPasswordChangeForm,
    	template_name='auth/password/password-change.html'), name='password_change'),

    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='auth/password/password-change-done.html'), name='password_change_done'),

    # Password Reset Views
    path('reset-password/', unauthenticated_user(auth_views.PasswordResetView.as_view(form_class=UserPasswordResetRequestForm,
        template_name='auth/password/password-reset.html', html_email_template_name='auth/verification/password_reset_html_email.html')), name="password_reset"),

    path('reset-password/done/', unauthenticated_user(auth_views.PasswordResetDoneView.as_view(
        template_name='auth/password/password-reset-done.html')), name="password_reset_done"),

    path('reset/<uidb64>/<token>', unauthenticated_user(auth_views.PasswordResetConfirmView.as_view(form_class=UserPasswordResetForm,
        template_name='auth/password/password-reset-confirm.html')), name="password_reset_confirm"),

    path('reset/done/', unauthenticated_user(auth_views.PasswordResetCompleteView.as_view(
        template_name='auth/password/password-reset-complete.html')), name="password_reset_complete"),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error Handlers
handler403 = 'error_handlers.views.handle_403'
handler404 = 'error_handlers.views.handle_404'
handler500 = 'error_handlers.views.handle_500'

assets/urls.py
from django.urls import path
from . import views

app_name = 'assets'

urlpatterns = [
    path('list', views.listed, name='list'),
    path('details/<uuid:id>', views.details, name='details'),
    path('update/<uuid:id>', views.update, name='update'),
    path('delete/<uuid:id>', views.delete, name='delete'),
    path('status/<uuid:id>', views.status, name='status'),
    path('add', views.add, name='add'),
    path('search/<str:page>', views.search, name='search'),
    path('assigned-list', views.assigned_list, name='assigned_list'),
    path('unassigned-list', views.unassigned_list, name='unassigned_list'),
    path('assign-asset', views.assign_asset, name='assign_asset'),
    path('reassign-asset/<uuid:id>', views.reassign_asset, name='reassign_asset'),
    path('delete-assign/<uuid:id>', views.delete_assign, name='delete_assign'),
    path('delete-assign-asset-list/<uuid:id>', views.delete_assign_asset_list, name='delete_assign_asset_list'),
    path('assign_asset_search/<str:page>', views.assign_asset_search, name='assign_asset_search'),
    path('change-status/<str:id>/',views.change_status,name='change_status'),
    path('status-repair-to-release/<str:id>/',views.release_asset,name='release'),
    path('status-ready-to-assign/<str:id>/',views.assign_assets,name='assigned'),
    path('update-assets-details/<str:id>/',views.update_in_detail,name='update_in_detail'),
    path('piechart_status_data/', views.pie_chart_assigned_status, name='piechart_status_data'),
    path('assets_by_status', views.pie_chart_status, name='pie_chart_status'),
    path('add_status',views.add_asset_status,name='add_asset_status'),
    path('asset_status_list',views.asset_status_list,name='asset_status_list'),
    path('asset_status_details/<uuid:id>',views.asset_status_details,name='asset_status_details'),
    path('edit_asset_status/<uuid:id>',views.edit_asset_status,name='edit_asset_status'),
    path('asset_status_search/<str:page>',views.asset_status_search,name='asset_status_search'),
    path('delete_asset_status/<uuid:id>',views.delete_asset_status,name='delete_asset_status'),
    path('assign-asset-in-asset-list/<uuid:id>', views.assign_asset_in_asset_list, name='assign_asset_in_asset_list'),
]

recycle_bin/urls.py
from django.urls import path
from . import views

app_name = 'recycle_bin'

urlpatterns = [
    path('deleted-products', views.deleted_products, name='deleted_products'),
    path('deleted-products/restore/<uuid:id>', views.deleted_products_restore, name='deleted_products_restore'),
    path('deleted-products/delete/<uuid:id>', views.deleted_products_permanently, name='deleted_products_permanently'),
    path('deleted-products-search/<str:page>', views.deleted_products_search, name='deleted_products_search'),
    
    path('deleted-vendors', views.deleted_vendors, name='deleted_vendors'),
    path('deleted-vendors/restore/<uuid:id>', views.deleted_vendor_restore, name='deleted_vendor_restore'),
    path('deleted-vendors/delete/<uuid:id>', views.deleted_vendor_permanently, name='deleted_vendor_permanently'),
    path('deleted-vendors-search/<str:page>', views.deleted_vendors_search, name='deleted_vendors_search'),

    path('deleted-assets', views.deleted_assets, name='deleted_assets'),
    path('deleted-assets/restore/<uuid:id>', views.deleted_asset_restore, name='deleted_asset_restore'),
    path('deleted-assets/delete/<uuid:id>', views.deleted_asset_permanently, name='deleted_asset_permanently'),
    path('deleted-assets-search/<str:page>', views.deleted_assets_search, name='deleted_assets_search'),

    path('deleted-users', views.deleted_users, name='deleted_users'),
    path('deleted-users/restore/<uuid:id>', views.deleted_user_restore, name='deleted_user_restore'),
    path('deleted-users/delete/<uuid:id>', views.deleted_user_permanently, name='deleted_user_permanently'),
    path('deleted-users-search/<str:page>', views.deleted_users_search, name='deleted_users_search'),


    path('deleted-locations', views.deleted_locations, name='deleted_locations'),
    path('deleted-locations/restore/<uuid:id>', views.deleted_locations_restore, name='deleted_locations_restore'),
    path('deleted-locations/delete/<uuid:id>', views.deleted_locations_permanently, name='deleted_locations_permanently'),
    path('deleted-locations-search/<str:page>', views.deleted_locations_search, name='deleted_locations_search'),


    path('deleted-departments', views.deleted_depertments, name='deleted_departments'),
    path('deleted-departments/restore/<uuid:id>', views.deleted_departments_restore, name='deleted_departments_restore'),
    path('deleted-departments/delete/<uuid:id>', views.deleted_departments_permanently, name='deleted_departments_permanently'),
    path('deleted-departments-search/<str:page>', views.deleted_departments_search, name='deleted_departments_search'),


    path('deleted_product_categories', views.deleted_product_categories, name='deleted_product_categories'),
    path('deleted_product_categories/restore/<uuid:id>', views.deleted_product_categories_restore, name='deleted_product_categories_restore'),
    path('deleted_product_categories/delete/<uuid:id>', views.deleted_product_categories_permanently, name='deleted_product_categories_permanently'),
    path('search_deleted_product_categories/<str:page>', views.search_deleted_product_categories, name='search_deleted_product_categories'),

    path('deleted_product_types', views.deleted_product_types, name='deleted_product_types'),
    path('deleted_product_types/restore/<uuid:id>', views.deleted_product_types_restore, name='deleted_product_types_restore'),
    path('deleted_product_types/delete/<uuid:id>', views.deleted_product_types_permanently, name='deleted_product_types_permanently'),
    path('deleted_product_types_search/<str:page>', views.deleted_product_types_search, name='deleted_product_types_search'),

    path('deleted_asset_status', views.deleted_asset_status, name='deleted_asset_status'),
    path('deleted_asset_status/restore/<uuid:id>', views.deleted_asset_status_restore, name='deleted_asset_status_restore'),
    path('deleted_asset_status/delete/<uuid:id>', views.deleted_asset_status_permanently, name='deleted_asset_status_permanently'),
    path('deleted_asset_status_search/<str:page>', views.deleted_asset_status_search, name='deleted_asset_status_search'),
]

roles/urls.py
from django.urls import path
from .views import *

app_name = 'roles'

urlpatterns = [
    path('list', list, name='list'),
    path('add', add, name='add'),
    path('update/<str:name>', update, name='update'),
    path('delete/<str:name>', delete, name='delete'),
    path('status/<str:name>', status, name='status'),
    path('search/<str:page>', search, name='search'),
]

upload/urls.py
from django.urls import path
from .views import *


app_name = 'upload'

urlpatterns = [
    path('vendors', vendor_list, name='vendor_list'),
    path('vendors/export/csv', export_vendors_csv, name='export_vendors_csv'),
    path('vendors/import/csv', import_vendors_csv, name = 'import_vendors_csv'),
    
    path('locations', location_list, name='location_list'),
    path('locations/export/csv', export_locations_csv, name='export_locations_csv'),
    path('locations/import/csv', import_locations_csv, name = 'import_locations_csv'),

    path('product-types', product_type_list, name='product_type_list'),
    path('product-types/export/csv', export_product_types_csv, name='export_product_types_csv'),
    path('product-types/import/csv', import_product_types_csv, name ='import_product_types_csv' ),

    path('product-categories', product_category_list, name='product_category_list'),
    path('product-categories/export/csv', export_product_categories_csv, name='export_product_categories_csv'),
    path('product-categories/import/csv', import_product_catagories_csv, name='import_product_catagories_csv'),
    
    path('departments', department_list, name = 'department_list' ),
    path('departments/export/csv', export_departments_csv , name='export_departments_csv'),
    path('departments/import/csv', import_departments_csv , name='import_departments_csv'),
    path('compare-data', render_to_mapper_modal, name='compare_data'),
    path('create-obj-department',create_matched_data_from_csv_department, name='create_data'),
    path('create-obj-location',create_matched_data_from_csv_locations,name='create-location-data'),
]

recycle_bin/models.py
from django.db import models

# Create your models here.

templates/recycle_bin/deleted-Product-types.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="page-heading">
    <div class="d-flex justify-content-between">
        <div class="page-title">
            <h3>Deleted Product Types</h3>
            <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                    <li class="breadcrumb-item" aria-current="page">Product Types</li>
                    <li class="breadcrumb-item active" aria-current="page">Trash</li>
                </ol>
            </nav>
        </div>
        <div>
            <a href="{% url 'dashboard:product_type_list' %}" class="btn btn-sm btn-outline-info my-3">Back to Product Types</a>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-body">
                {% if page_object %}
                    <div class="d-flex justify-content-end my-2 gap-2">
                        <input name="search_text" type="search" class='dataTable-input' autocomplete="off" placeholder='Search here...'
                            hx-get="{% url 'recycle_bin:deleted_product_types_search' page_object.number %}" hx-trigger="keyup changed delay:500ms, search" hx-target="#search_result">
                    </div>
                {% endif %}
                <table class="table table-hover" id="table1">
                    <thead>
                            <tr>
                                <th>Sl No.</th>
                                <th>Type Name</th>
                                <th>Actions</th>
                            </tr>
                    </thead>
                    {% if page_object %}
                        <tbody id="search_result">
                            {% for products in page_object %}
                                <tr>
                                    <td>{{ page_object.start_index|add:forloop.counter0 }}</td>
                                    <td>{{ products.name }}</td>
                                    <td>
                                        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                            <form action="{% url 'recycle_bin:deleted_product_types_restore' products.id %}" method="post" onsubmit="return confirm('Are you sure you want to restore this?')">  
                                                {% csrf_token %}
                                                <button type="submit" value="Delete" class="btn btn-sm btn-success"><i class="bi bi-arrow-repeat"></i></button>
                                            </form>
                                            <form action="{% url 'recycle_bin:deleted_product_types_permanently' products.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this permanently?')">  
                                                {% csrf_token %}
                                                <button type="submit" value="Delete" class="btn btn-sm btn-danger"><i class="bi bi-trash3-fill"></i></button>
                                            </form>
                                        </div>
                                    </td>   
                                </tr>
                            {% endfor %}
                        </tbody>
                    {% else %}
                      <div class="alert alert-info" role="alert">
                           No record available!
                      </div>
                    {% endif %}
                </table>
                {% include 'commons/pagination.html' %}
            </div>
        </div>

    </section>
</div>
{% endblock content%}

templates/recycle_bin/deleted-asset-status.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="page-heading">
    <div class="d-flex justify-content-between">
        <div class="page-title">
            <h3>Deleted Asset Status</h3>
            <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                    <li class="breadcrumb-item" aria-current="page">Asset Status</li>
                    <li class="breadcrumb-item active" aria-current="page">Trash</li>
                </ol>
            </nav>
        </div>
        <div>
            <a href="{% url 'assets:asset_status_list' %}" class="btn btn-sm btn-outline-info my-3">Back to Asset Status</a>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-body">
                {% if page_object %}
                    <div class="d-flex justify-content-end my-2 gap-2">
                        <input name="search_text" type="search" class='dataTable-input' autocomplete="off" placeholder='Search here...'
                            hx-get="{% url 'recycle_bin:deleted_asset_status_search' page_object.number %}" hx-trigger="keyup changed delay:500ms, search" hx-target="#search_result">
                    </div>
                {% endif %}
                <table class="table table-hover" id="table1">
                    <thead>
                            <tr>
                                <th>Sl No.</th>
                                <th>Asset Status Name</th>
                                <th>Actions</th>
                            </tr>
                        </thead>      
                        {% if page_object %}
                        <tbody id="search_result">
                            {% for products in page_object %}
                                <tr>
                                    <td>{{ page_object.start_index|add:forloop.counter0 }}</td>
                                    <td>{{ products.name }}</td>
                                    <td>
                                        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                            <form action="{% url 'recycle_bin:deleted_asset_status_restore' products.id %}" method="post" onsubmit="return confirm('Are you sure you want to restore this?')">  
                                                {% csrf_token %}
                                                <button type="submit" value="Delete" class="btn btn-sm btn-success"><i class="bi bi-arrow-repeat"></i></button>
                                            </form>
                                            <form action="{% url 'recycle_bin:deleted_asset_status_permanently' products.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this permanently?')">  
                                                {% csrf_token %}
                                                <button type="submit" value="Delete" class="btn btn-sm btn-danger"><i class="bi bi-trash3-fill"></i></button>
                                            </form>
                                        </div>
                                    </td>   
                                </tr>
                            {% endfor %}
                        </tbody>
                    {% else %}
                      <div class="alert alert-info" role="alert">
                           No record available!
                      </div>
                    {% endif %}
                </table>
                {% include 'commons/pagination.html' %}
            </div>
        </div>

    </section>
</div>
{% endblock content%}

templates/recycle_bin/deleted-assets.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="page-heading">
    <div class="d-flex justify-content-between">
        <div class="page-title">
            <h3>Deleted Assets</h3>
            <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                    <li class="breadcrumb-item" aria-current="page">Assets</li>
                    <li class="breadcrumb-item active" aria-current="page">Trash</li>
                </ol>
            </nav>
        </div>
        <div>
            <a href="{% url 'assets:list' %}" class="btn btn-sm btn-outline-info my-3">Back to Asset</a>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-body">
                {% if page_object %}
                    <div class="d-flex justify-content-end my-2 gap-2">
                        <input name="search_text" type="search" class='dataTable-input' autocomplete="off" placeholder='Search here...'
                            hx-get="{% url 'recycle_bin:deleted_assets_search' page_object.number %}" hx-trigger="keyup changed delay:500ms, search" hx-target="#search_result">
                    </div>
                {% endif %}
                <table class="table table-hover" id="table1">
                    <thead>
                        <tr>
                            <th>Sl No.</th>
                            <th>Asset Name</th>
                            <th>Serial No.</th>
                            <th>Product Type</th>
                            <th>Product</th>
                            <th>Vendor</th>
                            <th>Datetime</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    {% if page_object %}
                    <tbody id="search_result">
                          {% for asset in page_object %}
                        <tr>
                            <td>{{page_object.start_index|add:forloop.counter0}}</td>
                            <td>{{asset.name}}</td>
                            <td>{{asset.serial_no}}</td>
                            <td>{{asset.product.product_type}}</td>
                            <td>{{asset.product}}</td>
                            <td>{{asset.vendor}}</td>
                            <td>{{asset.updated_at}}</td>
                            <td>
                                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                    <form action="{% url 'recycle_bin:deleted_asset_restore' asset.id %}" method="post" onsubmit="return confirm('Are you sure you want to restore this?')">  
                                        {% csrf_token %}
                                        <button type="submit" value="Delete" class="btn btn-sm btn-success"><i class="bi bi-arrow-repeat"></i></button>
                                    </form>
                                    <form action="{% url 'recycle_bin:deleted_asset_permanently' asset.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this permanently?')">  
                                        {% csrf_token %}
                                        <button type="submit" value="Delete" class="btn btn-sm btn-danger"><i class="bi bi-trash3-fill"></i></button>
                                    </form>
                                </div>
                            </td>   
                        </tr>
                        {% endfor %}
                    </tbody>
                    {% else %}
                      <div class="alert alert-info" role="alert">
                           No record available!
                      </div>
                    {% endif %}
                </table>
                {% include 'commons/pagination.html' %}
            </div>
        </div>

    </section>
</div>
{% endblock content%}

templates/recycle_bin/deleted-products.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="page-heading">
    <div class="d-flex justify-content-between">
        <div class="page-title">
            <h3>Deleted Products</h3>
            <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                    <li class="breadcrumb-item" aria-current="page">Products</li>
                    <li class="breadcrumb-item active" aria-current="page">Trash</li>
                </ol>
            </nav>
        </div>
        <div>
            <a href="{% url 'products:list' %}" class="btn btn-sm btn-outline-info my-3">Back to Products</a>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-body">
                {% if page_object %}
                    <div class="d-flex justify-content-end my-2 gap-2">
                        <input name="search_text" type="search" class='dataTable-input' autocomplete="off" placeholder='Search here...'
                            hx-get="{% url 'recycle_bin:deleted_products_search' page_object.number %}" hx-trigger="keyup changed delay:500ms, search" hx-target="#search_result">
                    </div>
                {% endif %}
                <table class="table table-hover" id="table1">
                    <thead>
                        <tr>
                            <th>Sl No.</th>
                            <th>Product Image</th>
                            <th>Product Name</th>
                            <th>Product Type</th>
                            <th>Product Category</th>
                            <th>Datetime</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    {% if page_object %}
                    <tbody id="search_result">
                        {% for product in page_object %}
                        <tr>
                            <td>{{page_object.start_index|add:forloop.counter0}}</td>
                            <td>{% if product.product_picture %} <img src="{{product.product_picture.url}}" class="rounded" width="100" height="80" /> {% else %} Not uploaded {% endif %}</td>
                            <td>{{product.name}}</td>
                            <td>{{product.product_type}}</td>
                            <td>{{product.product_category}}</td>
                            <td>{{product.updated_at}}</td>
                            <td>
                                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                      <form action="{% url 'recycle_bin:deleted_products_restore' product.id %}" method="post" onsubmit="return confirm('Are you sure you want to restore it?')">
                                        {% csrf_token %}
                                          <button type="submit" class="btn btn-success btn-sm" title="Restore"><i class="bi bi-arrow-repeat"></i></button>
                                      </form>

                                      <form action="{% url 'recycle_bin:deleted_products_permanently' product.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this permanently?')">
                                        {% csrf_token %}
                                          <button type="submit" class="btn btn-danger btn-sm" title="Delete"><i class="bi bi-trash3-fill"></i></button>
                                      </form>                
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    {% else %}
                      <div class="alert alert-info" role="alert">
                           No record available!
                      </div>
                    {% endif %}
                </table>
                {% include 'commons/pagination.html' %}
            </div>
        </div>
    </section>
</div>
{% endblock content%}

templates/recycle_bin/deleted-vendors.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="page-heading">
    <div class="d-flex justify-content-between">
        <div class="page-title">
            <h3>Deletd Vendors</h3>
            <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                    <li class="breadcrumb-item" aria-current="page">Asset Status</li>
                    <li class="breadcrumb-item active" aria-current="page">Trash</li>
                </ol>
            </nav>
        </div>
        <div>
            <a href="{% url 'vendors:list' %}" class="btn btn-sm btn-outline-info my-3">Back to Vendors</a>
        </div>
    </div>
    <section class="section">
        <div class="card">
            <div class="card-body">
                {% if page_object %}
                    <div class="d-flex justify-content-end my-2 gap-2">
                        <input name="search_text" type="search" class='dataTable-input' autocomplete="off" placeholder='Search here...'
                            hx-get="{% url 'recycle_bin:deleted_vendors_search' page_object.number %}" hx-trigger="keyup changed delay:500ms, search" hx-target="#search_result">
                    </div>
                {% endif %}
                <table class="table table-hover" id="table1">
                    <thead>
                        <tr>
                            <th>Sl No.</th>
                            <th>Vendor Name</th>
                            <th>Contact Person</th>
                            <th>Email</th>
                            <th>GSTIN No.</th>
                            <th>Phone No.</th>
                            <th>Datetime</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    {% if page_object %}
                    <tbody id="search_result">
                          {% for vendor in page_object %}
                        <tr>
                            <td>{{page_object.start_index|add:forloop.counter0}}</td>
                            <td>{{vendor.name}}</td>
                            <td>{{vendor.contact_person}}</td>
                            <td>{{vendor.email}}</td>
                            <td>{{vendor.gstin_number}}</td>
                            <td>{{vendor.phone}}</td>
                            <td>{{vendor.updated_at}}</td>
                            <td>
                                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                    <form action="{% url 'recycle_bin:deleted_vendor_restore' vendor.id %}" method="post" onsubmit="return confirm('Are you sure you want to restore this?')">  
                                        {% csrf_token %}
                                        <button type="submit" value="Delete" class="btn btn-sm btn-success"><i class="bi bi-arrow-repeat"></i></button>
                                    </form>
                                    <form action="{% url 'recycle_bin:deleted_vendor_permanently' vendor.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this permanently?')">  
                                        {% csrf_token %}
                                        <button type="submit" value="Delete" class="btn btn-sm btn-danger"><i class="bi bi-trash3-fill"></i></button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    {% else %}
                      <div class="alert alert-info" role="alert">
                           No record available!
                      </div>
                    {% endif %}
                </table>
                {% include 'commons/pagination.html' %}
            </div>
        </div>

    </section>
</div>
{% endblock content%}