AssetManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from authentication.forms import UserPasswordChangeForm, UserPasswordResetForm, UserPasswordResetRequestForm
from authentication.decorators import unauthenticated_user


urlpatterns = [
    path('secret/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('vendors/', include('vendors.urls', namespace='vendors')),
    path('products/', include('products.urls', namespace='products')),
    path('admin/', include('dashboard.urls', namespace='dashboard')),
    path('upload/', include('upload.urls', namespace='upload')),
    path('recycle-bin/', include('recycle_bin.urls', namespace='recycle_bin')),
    path('assets/', include('assets.urls', namespace='assets')),
    path('roles/', include('roles.urls', namespace='roles')),
    path('support/', include('support.urls', namespace='support')),
    path('users/', include('users.urls', namespace='users')),
    path('notifications/', include('notifications.urls', namespace='notifications')),

    # django smart select urls
    path('chaining/', include('smart_selects.urls')),

    # Password Change Views
    path('change-password/', auth_views.PasswordChangeView.as_view(form_class=UserPasswordChangeForm,
    	template_name='auth/password/password-change.html'), name='password_change'),

    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='auth/password/password-change-done.html'), name='password_change_done'),

    # Password Reset Views
    path('reset-password/', unauthenticated_user(auth_views.PasswordResetView.as_view(form_class=UserPasswordResetRequestForm,
        template_name='auth/password/password-reset.html', html_email_template_name='auth/verification/password_reset_html_email.html')), name="password_reset"),

    path('reset-password/done/', unauthenticated_user(auth_views.PasswordResetDoneView.as_view(
        template_name='auth/password/password-reset-done.html')), name="password_reset_done"),

    path('reset/<uidb64>/<token>', unauthenticated_user(auth_views.PasswordResetConfirmView.as_view(form_class=UserPasswordResetForm,
        template_name='auth/password/password-reset-confirm.html')), name="password_reset_confirm"),

    path('reset/done/', unauthenticated_user(auth_views.PasswordResetCompleteView.as_view(
        template_name='auth/password/password-reset-complete.html')), name="password_reset_complete"),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error Handlers
handler403 = 'error_handlers.views.handle_403'
handler404 = 'error_handlers.views.handle_404'
handler500 = 'error_handlers.views.handle_500'

assets/urls.py
from django.urls import path
from . import views

app_name = 'assets'

urlpatterns = [
    path('list', views.listed, name='list'),
    path('details/<uuid:id>', views.details, name='details'),
    path('update/<uuid:id>', views.update, name='update'),
    path('delete/<uuid:id>', views.delete, name='delete'),
    path('status/<uuid:id>', views.status, name='status'),
    path('add', views.add, name='add'),
    path('search/<str:page>', views.search, name='search'),
    path('assigned-list', views.assigned_list, name='assigned_list'),
    path('unassigned-list', views.unassigned_list, name='unassigned_list'),
    path('assign-asset', views.assign_asset, name='assign_asset'),
    path('reassign-asset/<uuid:id>', views.reassign_asset, name='reassign_asset'),
    path('delete-assign/<uuid:id>', views.delete_assign, name='delete_assign'),
    path('delete-assign-asset-list/<uuid:id>', views.delete_assign_asset_list, name='delete_assign_asset_list'),
    path('assign_asset_search/<str:page>', views.assign_asset_search, name='assign_asset_search'),
    path('change-status/<str:id>/',views.change_status,name='change_status'),
    path('status-repair-to-release/<str:id>/',views.release_asset,name='release'),
    path('status-ready-to-assign/<str:id>/',views.assign_assets,name='assigned'),
    path('update-assets-details/<str:id>/',views.update_in_detail,name='update_in_detail'),
    path('piechart_status_data/', views.pie_chart_assigned_status, name='piechart_status_data'),
    path('assets_by_status', views.pie_chart_status, name='pie_chart_status'),
    path('add_status',views.add_asset_status,name='add_asset_status'),
    path('asset_status_list',views.asset_status_list,name='asset_status_list'),
    path('asset_status_details/<uuid:id>',views.asset_status_details,name='asset_status_details'),
    path('edit_asset_status/<uuid:id>',views.edit_asset_status,name='edit_asset_status'),
    path('asset_status_search/<str:page>',views.asset_status_search,name='asset_status_search'),
    path('delete_asset_status/<uuid:id>',views.delete_asset_status,name='delete_asset_status'),
    path('assign-asset-in-asset-list/<uuid:id>', views.assign_asset_in_asset_list, name='assign_asset_in_asset_list'),
]

dashboard/urls.py
from django.urls import path
from . import views
from .views import global_search_views
app_name = 'dashboard'

urlpatterns = [
     
    # location urls
    path('locations/list', views.locations, name='locations'),
    path('locations/add', views.add_location, name='add_location'),
    path('locations/details/<uuid:id>', views.location_details, name='location_details'),
    path('locations/update/<uuid:id>', views.update_location, name='update_location'),
    path('locations/delete/<uuid:id>', views.delete_location, name='delete_location'),
    path('locations/status/<uuid:id>', views.location_status, name='location_status'),
    path('locations/search/<str:page>', views.search_location, name='search_location'),

    # department urls
    path('departments/list', views.departments, name='departments'),
    path('departments/detail/<uuid:id>', views.department_details, name='department_details'),
    path('departments/updates/<uuid:id>', views.update_department, name='update_department'),
    path('departments/add', views.add_department, name='add_department'),
    path('departments/delete/<uuid:id>', views.delete_department, name='delete_department'),
    path('departments/status/<uuid:id>', views.department_status, name='department_status'),
    path('departments/search/<str:page>', views.search_department, name='search_department'),

    # product type urls
    path('product-types/list', views.product_type_list, name='product_type_list'),
    path('product-types/add', views.add_product_type, name='add_product_type'),
    path('product-types/details/<uuid:id>', views.product_type_details, name='product_type_details'),
    path('product-types/update/<uuid:id>', views.update_product_type, name='update_product_type'),
    path('product-types/delete/<uuid:id>', views.delete_product_type, name='delete_product_type'),
    path('product-types/status/<uuid:id>', views.product_type_status, name='product_type_status'),
    path('product-types/search/<str:page>', views.search_product_type, name='search_product_type'),

    # product category urls
    path('product-categories/list', views.product_category_list, name='product_category_list'),
    path('product-categories/add', views.add_product_category,name='add_product_category'),
    path('product-categories/details/<uuid:id>', views.product_category_details, name='product_category_details'),
    path('product-categories/delete/<uuid:id>', views.delete_product_category, name='delete_product_category'),
    path('product-categories/update/<uuid:id>', views.update_product_category, name='update_product_category'),
    path('product-categories/status/<uuid:id>', views.product_category_status, name='product_category_status'),
    path('product-categories/search/<str:page>', views.search_product_category, name='search_product_category'),


    # #product sub category urls
    # path('product-sub-categories/list', product_sub_category_views.product_sub_category_list, name='product_sub_category_list'),
    # path('product-sub-categories/add', product_sub_category_views.add_product_sub_category, name='add_product_sub_category'),
    # path('product-sub-categories/details/<uuid:id>', product_sub_category_views.product_sub_category_details, name='product_sub_category_details'),
    # path('product-sub-categories/delete/<uuid:id>', product_sub_category_views.delete_product_sub_category, name='delete_product_sub_category'),
    # path('product-sub-categories/update/<uuid:id>', product_sub_category_views.update_product_sub_category, name='update_product_sub_category'),
    # path('product-sub-categories/status/<uuid:id>', product_sub_category_views.product_sub_category_status, name='product_sub_category_status'),
    # path('product-sub-categories/search/<str:page>', product_sub_category_views.search_product_sub_category, name='search_product_sub_category'),
    path('get-subcategories/',views.get_subcategories, name='get_subcategories'),
     
     
     
     
    path('global-search/', global_search_views.global_search, name='global_search'),
]

recycle_bin/urls.py
from django.urls import path
from . import views

app_name = 'recycle_bin'

urlpatterns = [
    path('deleted-products', views.deleted_products, name='deleted_products'),
    path('deleted-products/restore/<uuid:id>', views.deleted_products_restore, name='deleted_products_restore'),
    path('deleted-products/delete/<uuid:id>', views.deleted_products_permanently, name='deleted_products_permanently'),
    path('deleted-products-search/<str:page>', views.deleted_products_search, name='deleted_products_search'),
    
    path('deleted-vendors', views.deleted_vendors, name='deleted_vendors'),
    path('deleted-vendors/restore/<uuid:id>', views.deleted_vendor_restore, name='deleted_vendor_restore'),
    path('deleted-vendors/delete/<uuid:id>', views.deleted_vendor_permanently, name='deleted_vendor_permanently'),
    path('deleted-vendors-search/<str:page>', views.deleted_vendors_search, name='deleted_vendors_search'),

    path('deleted-assets', views.deleted_assets, name='deleted_assets'),
    path('deleted-assets/restore/<uuid:id>', views.deleted_asset_restore, name='deleted_asset_restore'),
    path('deleted-assets/delete/<uuid:id>', views.deleted_asset_permanently, name='deleted_asset_permanently'),
    path('deleted-assets-search/<str:page>', views.deleted_assets_search, name='deleted_assets_search'),

    path('deleted-users', views.deleted_users, name='deleted_users'),
    path('deleted-users/restore/<uuid:id>', views.deleted_user_restore, name='deleted_user_restore'),
    path('deleted-users/delete/<uuid:id>', views.deleted_user_permanently, name='deleted_user_permanently'),
    path('deleted-users-search/<str:page>', views.deleted_users_search, name='deleted_users_search'),


    path('deleted-locations', views.deleted_locations, name='deleted_locations'),
    path('deleted-locations/restore/<uuid:id>', views.deleted_locations_restore, name='deleted_locations_restore'),
    path('deleted-locations/delete/<uuid:id>', views.deleted_locations_permanently, name='deleted_locations_permanently'),
    path('deleted-locations-search/<str:page>', views.deleted_locations_search, name='deleted_locations_search'),


    path('deleted-departments', views.deleted_depertments, name='deleted_departments'),
    path('deleted-departments/restore/<uuid:id>', views.deleted_departments_restore, name='deleted_departments_restore'),
    path('deleted-departments/delete/<uuid:id>', views.deleted_departments_permanently, name='deleted_departments_permanently'),
    path('deleted-departments-search/<str:page>', views.deleted_departments_search, name='deleted_departments_search'),


    path('deleted_product_categories', views.deleted_product_categories, name='deleted_product_categories'),
    path('deleted_product_categories/restore/<uuid:id>', views.deleted_product_categories_restore, name='deleted_product_categories_restore'),
    path('deleted_product_categories/delete/<uuid:id>', views.deleted_product_categories_permanently, name='deleted_product_categories_permanently'),
    path('search_deleted_product_categories/<str:page>', views.search_deleted_product_categories, name='search_deleted_product_categories'),

    path('deleted_product_types', views.deleted_product_types, name='deleted_product_types'),
    path('deleted_product_types/restore/<uuid:id>', views.deleted_product_types_restore, name='deleted_product_types_restore'),
    path('deleted_product_types/delete/<uuid:id>', views.deleted_product_types_permanently, name='deleted_product_types_permanently'),
    path('deleted_product_types_search/<str:page>', views.deleted_product_types_search, name='deleted_product_types_search'),

    path('deleted_asset_status', views.deleted_asset_status, name='deleted_asset_status'),
    path('deleted_asset_status/restore/<uuid:id>', views.deleted_asset_status_restore, name='deleted_asset_status_restore'),
    path('deleted_asset_status/delete/<uuid:id>', views.deleted_asset_status_permanently, name='deleted_asset_status_permanently'),
    path('deleted_asset_status_search/<str:page>', views.deleted_asset_status_search, name='deleted_asset_status_search'),
]

roles/urls.py
from django.urls import path
from .views import *

app_name = 'roles'

urlpatterns = [
    path('list', list, name='list'),
    path('add', add, name='add'),
    path('update/<str:name>', update, name='update'),
    path('delete/<str:name>', delete, name='delete'),
    path('status/<str:name>', status, name='status'),
    path('search/<str:page>', search, name='search'),
]

assets/models.py
import uuid, os
from django.db import models
from dashboard.models import Location, TimeStampModel, Organization, SoftDeleteModel
from products.models import Product
from vendors.models import Vendor
from django.db.models import Sum
from authentication.models import User
from simple_history.models import HistoricalRecords


def path_and_rename(instance, filename):
    upload_to = 'asset_images/'
    ext = filename.split('.')[-1]
    if instance.pk:
        filename = '{}.{}'.format(instance.pk, ext)
    else:
        filename = '{}.{}'.format(uuid.uuid4().hex, ext)
    return os.path.join(upload_to, filename)

class AssetSpecification(TimeStampModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    asset = models.ForeignKey('Asset', models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    value = models.CharField(max_length=255, blank=True, null=True)

class AssetStatus(TimeStampModel, SoftDeleteModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, blank=True, null=True)
    can_modify=models.BooleanField(default=True)
    organization = models.ForeignKey(Organization, models.DO_NOTHING, blank=True, null=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.name

class Asset(TimeStampModel, SoftDeleteModel):
    STATUS_CHOICES = [
        (0, 'Assigned'),
        (1, 'Available'),
        (2, 'Repair Required'),
        (3, 'Lost/Stolen'),
        (4, 'Broken'),
        (5, 'Ready To Deploy'),
        (6, 'Out for Repair')
    ]
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tag = models.CharField(max_length=255, blank=False, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    serial_no = models.CharField(max_length=45, blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    asset_status=models.ForeignKey(AssetStatus, models.DO_NOTHING, null=True, blank=True)
    purchase_date = models.DateField(blank=True, null=True)
    warranty_expiry_date = models.DateField(blank=True, null=True)
    purchase_type = models.CharField(max_length=45, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    is_assigned = models.BooleanField(default=False)
    product = models.ForeignKey(Product, models.PROTECT, blank=True, null=True)
    vendor = models.ForeignKey(Vendor, models.PROTECT, blank=True, null=True)
    location = models.ForeignKey(Location, models.DO_NOTHING, blank=True, null=True)
    organization = models.ForeignKey(Organization, models.DO_NOTHING, blank=True, null=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.name

class AssetImage(models.Model):
    asset = models.ForeignKey('Asset', on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=path_and_rename, blank=True, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return f"Image for {self.asset.name or self.asset.id}"
    # @classmethod
    # def total_asset_cost(self):
    #     return self.objects.all().aggregate(total_cost=Sum('price')).get('total_cost',0)

    # def __str__(self):
    #     return f'{self.name} ({self.serial_no})'

class AssignAsset(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    asset = models.ForeignKey(Asset, models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(User, models.DO_NOTHING, blank=True, null=True)                          
    assigned_date = models.DateField(auto_now_add=True,blank=True, null=True)

templates/assets/asset_status_list.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="page-heading">
    <div class="d-flex justify-content-between">
        <div class="page-title">
            <h3>Asset Status</h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Asset Status</li>
                </ol>
            </nav>
        </div>
        <div class="d-flex">
            {% if perms.authentication.add_asset_status %}
                <div>
                    <button type="button" class="btn btn-sm btn-outline-info my-3 me-2" 
                        hx-get="{% url 'assets:add_asset_status' %}" hx-target="#add-asset-status-modal-content"
                        data-bs-toggle="modal" data-bs-target="#add-asset-status-modal"
                    >Add Asset Status</button>
                </div>
            {% endif %}
            <a href="{% url 'recycle_bin:deleted_asset_status' %}" class="btn btn-sm btn-outline-info my-3 trash-btn d-flex align-items-center position-relative">
                <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-trash" style="margin-bottom: 2px;"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 7l16 0" /><path d="M10 11l0 6" /><path d="M14 11l0 6" /><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" /><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                </svg>Trash</a>
        </div>
    </div>
    <section class="section">
        <!-- add modal -->
        <div class="modal fade text-left" id="add-asset-status-modal" tabindex="-1" role="dialog"
            aria-labelledby="myModalLabel160" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
                <div id="add-asset-status-modal-content" class="modal-content" hx-target="this"></div>
            </div>
        </div>

        <!-- update modal -->
        <div class="modal fade text-left" id="update-asset-status-modal" tabindex="-1" role="dialog"
            aria-labelledby="myModalLabel160" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
                <div id="update-asset-status-modal-content" class="modal-content" hx-target="this"></div>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                {% if page_object %}
                    <div class="d-flex justify-content-end my-2 gap-2">
                        <input name="search_text" type="search" class='dataTable-input' autocomplete="off" placeholder='Search here...'
                            hx-get="{% url 'assets:asset_status_search' page_object.number %}" 
                            hx-trigger="keyup changed delay:500ms, search" hx-target="#search_result">
                    </div>
                {% endif %}
                <div class="table-responsive">
                    <table class="table table-hover" id="table1">
                        <thead>
                            <tr>
                                <th>Sl No.</th>
                                <th>Asset Status Name</th>
                                <th>Status</th>
                                {% if perms.authentication.edit_asset_status or perms.authentication.asset_status %}
                                    <th>Actions</th>
                                {% endif %}
                            </tr>
                        </thead>      
                        {% if page_object %}
                        <tbody id="search_result">
                            {% for products in page_object %}
                                <tr>
                                    <td>{{ page_object.start_index|add:forloop.counter0 }}</td>
                                    <td>{{ products.name }}</td>
                                    <td> 
                                        {% if request.user.is_superuser %}
                                            <div class="form-check form-switch">
                                                <input 
                                                    class="form-check-input"
                                                    hx-post="{% url 'dashboard:product_category_status' products.id %}" 
                                                    hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'
                                                    type="checkbox" {% if products.status %} checked {% endif %}
                                                    style="cursor: pointer;" {% if products.can_modify is False %} disabled {% endif %}
                                                >
                                            </div> 
                                        {% else %}
                                            {% if products.status %} Active {% else %} Inactive {% endif %}
                                        {% endif %}
                                    </td>
                                    {% if products.can_modify %}
                                        {% if perms.authentication.edit_asset_status or perms.authentication.asset_status %}
                                            <td>
                                                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                                    {% if request.user.is_superuser %}
                                                        <a href="{% url 'assets:asset_status_details' products.id %}" class="btn btn-sm btn-success">
                                                            <i class="bi bi-eye-fill"></i>
                                                        </a>
                                                    {% endif %}

                                                    {% if perms.authentication.edit_asset_status %}
                                                        <button type="button" class="btn btn-info"
                                                            hx-get="{% url 'assets:edit_asset_status' products.id %}"
                                                            hx-target="#update-asset-status-modal-content" 
                                                            data-bs-toggle="modal" data-bs-target="#update-asset-status-modal"
                                                            {% if products.can_modify is False %} disabled {% endif %}
                                                        >
                                                            <i class="bi bi-pencil-square"></i>
                                                        </button>
                                                    {% endif %}

                                                    {% if perms.authentication.asset_status %}
                                                        <form action="{% url 'assets:delete_asset_status' products.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this?')">  
                                                            {% csrf_token %}
                                                            <button type="submit" class="btn btn-sm btn-danger" {% if products.can_modify is False %} disabled {% endif %}>
                                                                <i class="bi bi-trash3-fill"></i>
                                                            </button>
                                                        </form> 
                                                    {% endif %}
                                                </div>
                                            </td>
                                        {% endif %}

                                        {% else %}
                                            <td><div><p class="fw-bold">Actions are not allowed!</p></div></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                        {% else %}
                        <div class="alert alert-info" role="alert">
                             No record available!
                        </div>
                        {% endif %}
                    </table>
                    {% include 'commons/pagination.html' %}
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content %}

templates/assets/unassigned-list.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="page-heading">
    <div class="d-flex justify-content-between">
        <div class="page-title">
            <h3>Unassigned Asset</h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Unassigned Asset</li>
                </ol>
            </nav>
        </div>
        {% if perms.authentication.add_assign_asset %}
            <div>
                <!-- assign btn -->
                <button type="button"  
                    class="btn btn-sm btn-outline-info my-3 "
                    hx-get="{% url 'assets:assign_asset' %}" 
                    hx-target="#assign-asset-modal-content"
                    data-bs-toggle="modal" 
                    data-bs-target="#assign-asset-modal"
                >Assign Asset</button>
            </div>
        {% endif %}
    </div>
    <section class="section">
        <!-- assign modal -->
        <div class="modal fade text-left" id="assign-asset-modal" tabindex="-1" role="dialog"
            aria-labelledby="myModalLabel160" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div id="assign-asset-modal-content" class="modal-content" hx-target="this"></div>
            </div>
        </div>        
        <!-- reassign modal -->
        <div class="modal fade text-left" id="reassign-asset-modal" tabindex="-1" role="dialog"
            aria-labelledby="myModalLabel160" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div id="reassign-asset-modal-content" class="modal-content" hx-target="this"></div>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                {% if page_object %}
                    <a href="{% url 'assets:list' %}" class="btn btn btn-info">Asset List</a>
                    <div class="d-flex justify-content-end my-2 gap-2">
                        <input name="search_text" type="search" class='dataTable-input' autocomplete="off" placeholder='Search here...'
                            hx-get="{% url 'assets:assign_asset_search' page_object.number %}" hx-trigger="keyup changed delay:500ms, search" hx-target="#search_result">
                    </div>
                {% endif %}
                <table class="table table-hover text-center" id="table1">
                    <thead>
                        <tr>
                            <th>Sl No.</th>
                            <th>Asset Name</th>
                            <th>Serial No.</th>
                            {% if perms.authentication.reassign_assign_asset or perms.authentication.delete_assign_asset%}
                                <th>Actions</th>
                            {% endif %}
                        </tr>
                    </thead>
                    {% if page_object %}
                    <tbody id="search_result">
                          {% for assign_asset in page_object %}
                        <tr>
                            <td>{{page_object.start_index|add:forloop.counter0}}</td>
                            <td>{{assign_asset.name}}</td>
                            <td>{{assign_asset.serial_no}}</td>
                            <td>
                                <a href="{% url 'assets:details' assign_asset.id %}" class="btn btn-success"><i class="bi bi-eye-fill"></i></a>
                                {% if perms.authentication.reassign_assign_asset %}
                                <button type="button"  
                                    class="btn btn-info"
                                    hx-get="{% url 'assets:assign_asset_in_asset_list' assign_asset.id %}"
                                    hx-target="#assign-asset-modal-list-content"
                                    data-bs-toggle="modal"

                                    data-bs-target="#assign-asset-list-modal">
                                    Assign
                                </button>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    {% else %}
                      <div class="alert alert-info" role="alert">
                        No record available!
                      </div>
                    {% endif %}
                </table>
                {% include 'commons/pagination.html' %}
            </div>
            <div class="modal fade" id="assign-asset-list-modal" tabindex="-1" aria-labelledby="assignAssetLabel">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content" id="assign-asset-modal-list-content" hx-target="this"><!-- HTMX will inject modal content here -->
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content%}