AssetManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from authentication.forms import UserPasswordChangeForm, UserPasswordResetForm, UserPasswordResetRequestForm
from authentication.decorators import unauthenticated_user


urlpatterns = [
    path('secret/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('vendors/', include('vendors.urls', namespace='vendors')),
    path('products/', include('products.urls', namespace='products')),
    path('admin/', include('dashboard.urls', namespace='dashboard')),
    path('upload/', include('upload.urls', namespace='upload')),
    path('recycle-bin/', include('recycle_bin.urls', namespace='recycle_bin')),
    path('assets/', include('assets.urls', namespace='assets')),
    path('roles/', include('roles.urls', namespace='roles')),
    path('support/', include('support.urls', namespace='support')),
    path('users/', include('users.urls', namespace='users')),
    path('notifications/', include('notifications.urls', namespace='notifications')),

    # django smart select urls
    path('chaining/', include('smart_selects.urls')),

    # Password Change Views
    path('change-password/', auth_views.PasswordChangeView.as_view(form_class=UserPasswordChangeForm,
    	template_name='auth/password/password-change.html'), name='password_change'),

    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='auth/password/password-change-done.html'), name='password_change_done'),

    # Password Reset Views
    path('reset-password/', unauthenticated_user(auth_views.PasswordResetView.as_view(form_class=UserPasswordResetRequestForm,
        template_name='auth/password/password-reset.html', html_email_template_name='auth/verification/password_reset_html_email.html')), name="password_reset"),

    path('reset-password/done/', unauthenticated_user(auth_views.PasswordResetDoneView.as_view(
        template_name='auth/password/password-reset-done.html')), name="password_reset_done"),

    path('reset/<uidb64>/<token>', unauthenticated_user(auth_views.PasswordResetConfirmView.as_view(form_class=UserPasswordResetForm,
        template_name='auth/password/password-reset-confirm.html')), name="password_reset_confirm"),

    path('reset/done/', unauthenticated_user(auth_views.PasswordResetCompleteView.as_view(
        template_name='auth/password/password-reset-complete.html')), name="password_reset_complete"),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error Handlers
handler403 = 'error_handlers.views.handle_403'
handler404 = 'error_handlers.views.handle_404'
handler500 = 'error_handlers.views.handle_500'

dashboard/urls.py
from django.urls import path
from . import views
from .views import global_search_views
app_name = 'dashboard'

urlpatterns = [
     
    # location urls
    path('locations/list', views.locations, name='locations'),
    path('locations/add', views.add_location, name='add_location'),
    path('locations/details/<uuid:id>', views.location_details, name='location_details'),
    path('locations/update/<uuid:id>', views.update_location, name='update_location'),
    path('locations/delete/<uuid:id>', views.delete_location, name='delete_location'),
    path('locations/status/<uuid:id>', views.location_status, name='location_status'),
    path('locations/search/<str:page>', views.search_location, name='search_location'),

    # department urls
    path('departments/list', views.departments, name='departments'),
    path('departments/detail/<uuid:id>', views.department_details, name='department_details'),
    path('departments/updates/<uuid:id>', views.update_department, name='update_department'),
    path('departments/add', views.add_department, name='add_department'),
    path('departments/delete/<uuid:id>', views.delete_department, name='delete_department'),
    path('departments/status/<uuid:id>', views.department_status, name='department_status'),
    path('departments/search/<str:page>', views.search_department, name='search_department'),

    # product type urls
    path('product-types/list', views.product_type_list, name='product_type_list'),
    path('product-types/add', views.add_product_type, name='add_product_type'),
    path('product-types/details/<uuid:id>', views.product_type_details, name='product_type_details'),
    path('product-types/update/<uuid:id>', views.update_product_type, name='update_product_type'),
    path('product-types/delete/<uuid:id>', views.delete_product_type, name='delete_product_type'),
    path('product-types/status/<uuid:id>', views.product_type_status, name='product_type_status'),
    path('product-types/search/<str:page>', views.search_product_type, name='search_product_type'),

    # product category urls
    path('product-categories/list', views.product_category_list, name='product_category_list'),
    path('product-categories/add', views.add_product_category,name='add_product_category'),
    path('product-categories/details/<uuid:id>', views.product_category_details, name='product_category_details'),
    path('product-categories/delete/<uuid:id>', views.delete_product_category, name='delete_product_category'),
    path('product-categories/update/<uuid:id>', views.update_product_category, name='update_product_category'),
    path('product-categories/status/<uuid:id>', views.product_category_status, name='product_category_status'),
    path('product-categories/search/<str:page>', views.search_product_category, name='search_product_category'),


    # #product sub category urls
    # path('product-sub-categories/list', product_sub_category_views.product_sub_category_list, name='product_sub_category_list'),
    # path('product-sub-categories/add', product_sub_category_views.add_product_sub_category, name='add_product_sub_category'),
    # path('product-sub-categories/details/<uuid:id>', product_sub_category_views.product_sub_category_details, name='product_sub_category_details'),
    # path('product-sub-categories/delete/<uuid:id>', product_sub_category_views.delete_product_sub_category, name='delete_product_sub_category'),
    # path('product-sub-categories/update/<uuid:id>', product_sub_category_views.update_product_sub_category, name='update_product_sub_category'),
    # path('product-sub-categories/status/<uuid:id>', product_sub_category_views.product_sub_category_status, name='product_sub_category_status'),
    # path('product-sub-categories/search/<str:page>', product_sub_category_views.search_product_sub_category, name='search_product_sub_category'),
    path('get-subcategories/',views.get_subcategories, name='get_subcategories'),
     
     
     
     
    path('global-search/', global_search_views.global_search, name='global_search'),
]

recycle_bin/urls.py
from django.urls import path
from . import views

app_name = 'recycle_bin'

urlpatterns = [
    path('deleted-products', views.deleted_products, name='deleted_products'),
    path('deleted-products/restore/<uuid:id>', views.deleted_products_restore, name='deleted_products_restore'),
    path('deleted-products/delete/<uuid:id>', views.deleted_products_permanently, name='deleted_products_permanently'),
    path('deleted-products-search/<str:page>', views.deleted_products_search, name='deleted_products_search'),
    
    path('deleted-vendors', views.deleted_vendors, name='deleted_vendors'),
    path('deleted-vendors/restore/<uuid:id>', views.deleted_vendor_restore, name='deleted_vendor_restore'),
    path('deleted-vendors/delete/<uuid:id>', views.deleted_vendor_permanently, name='deleted_vendor_permanently'),
    path('deleted-vendors-search/<str:page>', views.deleted_vendors_search, name='deleted_vendors_search'),

    path('deleted-assets', views.deleted_assets, name='deleted_assets'),
    path('deleted-assets/restore/<uuid:id>', views.deleted_asset_restore, name='deleted_asset_restore'),
    path('deleted-assets/delete/<uuid:id>', views.deleted_asset_permanently, name='deleted_asset_permanently'),
    path('deleted-assets-search/<str:page>', views.deleted_assets_search, name='deleted_assets_search'),

    path('deleted-users', views.deleted_users, name='deleted_users'),
    path('deleted-users/restore/<uuid:id>', views.deleted_user_restore, name='deleted_user_restore'),
    path('deleted-users/delete/<uuid:id>', views.deleted_user_permanently, name='deleted_user_permanently'),
    path('deleted-users-search/<str:page>', views.deleted_users_search, name='deleted_users_search'),


    path('deleted-locations', views.deleted_locations, name='deleted_locations'),
    path('deleted-locations/restore/<uuid:id>', views.deleted_locations_restore, name='deleted_locations_restore'),
    path('deleted-locations/delete/<uuid:id>', views.deleted_locations_permanently, name='deleted_locations_permanently'),
    path('deleted-locations-search/<str:page>', views.deleted_locations_search, name='deleted_locations_search'),


    path('deleted-departments', views.deleted_depertments, name='deleted_departments'),
    path('deleted-departments/restore/<uuid:id>', views.deleted_departments_restore, name='deleted_departments_restore'),
    path('deleted-departments/delete/<uuid:id>', views.deleted_departments_permanently, name='deleted_departments_permanently'),
    path('deleted-departments-search/<str:page>', views.deleted_departments_search, name='deleted_departments_search'),


    path('deleted_product_categories', views.deleted_product_categories, name='deleted_product_categories'),
    path('deleted_product_categories/restore/<uuid:id>', views.deleted_product_categories_restore, name='deleted_product_categories_restore'),
    path('deleted_product_categories/delete/<uuid:id>', views.deleted_product_categories_permanently, name='deleted_product_categories_permanently'),
    path('search_deleted_product_categories/<str:page>', views.search_deleted_product_categories, name='search_deleted_product_categories'),

    path('deleted_product_types', views.deleted_product_types, name='deleted_product_types'),
    path('deleted_product_types/restore/<uuid:id>', views.deleted_product_types_restore, name='deleted_product_types_restore'),
    path('deleted_product_types/delete/<uuid:id>', views.deleted_product_types_permanently, name='deleted_product_types_permanently'),
    path('deleted_product_types_search/<str:page>', views.deleted_product_types_search, name='deleted_product_types_search'),

    path('deleted_asset_status', views.deleted_asset_status, name='deleted_asset_status'),
    path('deleted_asset_status/restore/<uuid:id>', views.deleted_asset_status_restore, name='deleted_asset_status_restore'),
    path('deleted_asset_status/delete/<uuid:id>', views.deleted_asset_status_permanently, name='deleted_asset_status_permanently'),
    path('deleted_asset_status_search/<str:page>', views.deleted_asset_status_search, name='deleted_asset_status_search'),
]

roles/urls.py
from django.urls import path
from .views import *

app_name = 'roles'

urlpatterns = [
    path('list', list, name='list'),
    path('add', add, name='add'),
    path('update/<str:name>', update, name='update'),
    path('delete/<str:name>', delete, name='delete'),
    path('status/<str:name>', status, name='status'),
    path('search/<str:page>', search, name='search'),
]

dashboard/views/department_views.py
from django.shortcuts import render
from django.contrib import messages
from dashboard.models import Department
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from dashboard.forms import DepartmentForm
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.db.models import Q


PAGE_SIZE = 10
ORPHANS = 1


def check_admin(user):
    return user.is_superuser


def manage_access(user):
    permissions_list = [
        'authentication.edit_department',
        'authentication.add_department',
        'authentication.delete_department',
    ]

    for permission in permissions_list:
        if user.has_perm(permission):
            return True

    return False


@login_required
@user_passes_test(manage_access)
def departments(request):
    department_list = Department.undeleted_objects.filter(
        organization=request.user.organization).order_by('-created_at')
    deleted_department_count=Department.deleted_objects.count()
    paginator = Paginator(department_list, PAGE_SIZE, orphans=ORPHANS)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    department_form = DepartmentForm()

    context = {
        'sidebar': 'admin',
        'submenu': 'department',
        'page_object': page_object,
        'department_form': department_form,
        'deleted_department_count':deleted_department_count,
        'title': 'Departments'
    }
    return render(request, 'dashboard/departments/list.html', context=context)


@login_required
@user_passes_test(check_admin)
def department_details(request, id):

    department = get_object_or_404(
        Department.undeleted_objects, pk=id, organization=request.user.organization)

    history_list = department.history.all()
    paginator = Paginator(history_list, 5, orphans=1)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    context = {'sidebar': 'admin', 'page_object': page_object,
               'submenu': 'department', 'department': department, 'title': 'Department - Details'}
    return render(request, 'dashboard/departments/detail.html', context=context)


@login_required
@permission_required('authentication.add_department')
def add_department(request):

    form = DepartmentForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            department = form.save(commit=False)
            department.organization = request.user.organization
            department.save()
            messages.success(request, 'Department added successfully')
            return HttpResponse(status=204)

    context = {"form": form, "modal_title": "Add Department"}
    return render(request, 'dashboard/departments/department-modal.html', context=context)


@login_required
@permission_required('authentication.edit_department')
def update_department(request, id):

    department = get_object_or_404(
        Department.undeleted_objects, pk=id, organization=request.user.organization)
    form = DepartmentForm(
        request.POST or None, instance=department)

    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, 'Department updated successfully')
            return HttpResponse(status=204)

    context = {"form": form, "modal_title": "Update Department"}
    return render(request, 'dashboard/departments/department-modal.html', context=context)


@login_required
@permission_required('authentication.delete_department')
def delete_department(request, id):

    if request.method == 'POST':
        department = get_object_or_404(
            Department.undeleted_objects, pk=id, organization=request.user.organization)
        department.status = False
        department.soft_delete()
        history_id = department.history.first().history_id
        department.history.filter(pk=history_id).update(history_type='-')
        messages.success(request, 'Department deleted successfully')
        return redirect(request.META.get('HTTP_REFERER'))

    return redirect('/')


@user_passes_test(check_admin)
def department_status(request, id):
    if request.method == "POST":
        department = get_object_or_404(
            Department.undeleted_objects, pk=id, organization=request.user.organization)
        department.status = False if department.status else True
        department.save()
    return HttpResponse(status=204)



@login_required
def search_department(request, page):
    search_text = request.GET.get('search_text').strip()
    if search_text:
        return render(request, 'dashboard/departments/departments-data.html', {
            'page_object': Department.undeleted_objects.filter(Q(organization=request.user.organization) & (Q(
                name__icontains=search_text) | Q(contact_person_name__icontains=search_text) | Q(contact_person_email__icontains=search_text) | Q(contact_person_phone__icontains=search_text)
            )).order_by('-created_at')[:10]
        })

    department_list = Department.undeleted_objects.filter(
        organization=request.user.organization).order_by('-created_at')
    paginator = Paginator(department_list, PAGE_SIZE, orphans=ORPHANS)
    page_number = page
    page_object = paginator.get_page(page_number)
    return render(request, 'dashboard/departments/departments-data.html', {'page_object': page_object})

dashboard/views/seeders.py
from dashboard.models import ProductCategory
from authentication.models import SeedFlag

def seed_parent_category(organization=None):
    default_parent_category = ['Root']
    for category in default_parent_category:
            ProductCategory.objects.get_or_create(
            name=category.strip(),
            organization=organization,
        )

    SeedFlag.objects.create(seeded=True)




def seed_parent_category(category=None, organization=None):
    default_parent_category = ['Root']
    if category:
        for category in  default_parent_category:
               ProductCategory.objects.get_or_create(
                name=category.strip(),
                organization=organization,
        )



    SeedFlag.objects.create(seeded=True)
    return True

templates/dashboard/product_category/detail.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Product Category Details</h3>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-first">
                <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                        <li class="breadcrumb-item" aria-current="page">Product Categories</li>
                        <li class="breadcrumb-item active" aria-current="page">Product Category Details</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <section class="section">
        <div>
            <a href="{% url 'dashboard:product_category_list' %}" class="btn btn-sm btn-outline-info my-3">Back to Product Category List</a>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-borderless">
                        <tbody>
                        <tr>
                            <th scope="row">Product Category Name</th>
                            <td>{{product_category.name}}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        {% include 'commons/history.html' %}
    </section>
</div>
{% endblock content%}

templates/dashboard/product_category/list.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
<div class="page-heading">
    <div class="d-flex justify-content-between align-items-center">
        <div class="page-title">
            <h3>Product Categories</h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Product Categories</li>
                </ol>
            </nav>
        </div>
        <div class="d-flex ">
            {% if perms.authentication.add_product_category %}
            <div class="d-flex justify-content-end">
                <div>
                    <button type="button" class="btn btn-sm btn-outline-info my-3 me-2" 
                        hx-get="{% url 'dashboard:add_product_category' %}" hx-target="#add-product-category-modal-content"
                        data-bs-toggle="modal" data-bs-target="#add-product-category-modal"
                    >Add Product Category</i></button>
                </div>
                
            </div>
            {% endif %}
            <a href="{% url 'recycle_bin:deleted_product_categories' %}" class="btn btn-sm btn-outline-info my-3 trash-btn d-flex align-items-center position-relative">
            <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-trash" style="margin-bottom: 2px;"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 7l16 0" /><path d="M10 11l0 6" /><path d="M14 11l0 6" /><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" /><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
            </svg>Trash</a>
        </div>

    </div>
    <section class="section">
        <!-- add modal -->
        <div class="modal fade text-left" id="add-product-category-modal" tabindex="-1" role="dialog"
            aria-labelledby="myModalLabel160" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
                <div id="add-product-category-modal-content" class="modal-content" hx-target="this"></div>
            </div>
        </div>
        <!-- update modal -->
        <div class="modal fade text-left" id="update-product-category-modal" tabindex="-1" role="dialog"
            aria-labelledby="myModalLabel160" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
                <div id="update-product-category-modal-content" class="modal-content" hx-target="this"></div>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                {% if page_object %}
                    <div class="d-flex justify-content-end my-2 gap-2">
                        <input name="search_text" type="search" class='dataTable-input' autocomplete="off" placeholder='Search here...'
                            hx-get="{% url 'dashboard:search_product_category' page_object.number %}" hx-trigger="keyup changed delay:500ms, search" hx-target="#search_result">
                    </div>
                {% endif %}
                <div class="table-responsive">
                    <table class="table table-hover" id="table1">
                        <thead>
                            <tr>
                                <th>Sl No.</th>
                                <th>Category Name</th>
                                <th>Parent Category Name</th>
                                <th>Status</th>
                                {% if perms.authentication.edit_product_category or perms.authentication.delete_product_category %}
                                    <th>Actions</th>
                                {% endif %}
                            </tr>
                        </thead>      
                        {% if page_object %}
                        <tbody id="search_result">
                            {% for products in page_object %}
                                <tr>
                                    <td>{{page_object.start_index|add:forloop.counter0}}</td>
                                    <td>{{products.name}}</td>
                                    <td>{{products.parent.name}}
                                        {% if products.parent.is_deleted %}
                                            <i class="bi bi-exclamation-triangle text-warning" title="Parent Category is deleted, please update or restore."></i>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if request.user.is_superuser %}
                                            <div class="form-check form-switch">
                                                <input 
                                                    class="form-check-input"
                                                    hx-post="{% url 'dashboard:product_category_status' products.id %}" 
                                                    hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'
                                                    type="checkbox" {% if products.status %} checked {% endif %}
                                                    style="cursor: pointer;"
                                                >
                                            </div>  
                                        {% else %}
                                            {% if products.status %} Active {% else %} Inactive {% endif %}
                                        {% endif %}
                                    </td>
                                    <td>
                                        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                            {% if request.user.is_superuser %}
                                                <a href="{% url 'dashboard:product_category_details' products.id %}" class="btn btn-success"><i class="bi bi-eye-fill"></i></a>
                                            {% endif %}
                                            {% if perms.authentication.edit_product_category %}
                                                <button type="button" class="btn btn-info"
                                                    hx-get="{% url 'dashboard:update_product_category' products.id %}"
                                                    hx-target="#update-product-category-modal-content" 
                                                    data-bs-toggle="modal" data-bs-target="#update-product-category-modal"
                                                ><i class="bi bi-pencil-square"></i></button>
                                            {% endif%}
                                            {% if perms.authentication.delete_product_category %}
                                                <form action="{% url 'dashboard:delete_product_category' products.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this?')">  
                                                    {% csrf_token %}
                                                    <button type="submit" value="Delete" class="btn btn-sm btn-danger"><i class="bi bi-trash3-fill"></i></button>
                                                </form>  
                                            {% endif %}
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                        {% else %}
                        <div class="alert alert-info" role="alert">
                             No record available!
                        </div>
                      {% endif %}
                  </table>
                {% include 'commons/pagination.html' %}
            </div>
        </div>
    </section>
</div>
{% endblock content%}

templates/dashboard/product_category/product-categories-data.html
{% if page_object %}
    {% for products in page_object %}
    <tr>
        <td>
            {% if page_object.start_index %}
                {{page_object.start_index|add:forloop.counter0}}
            {% else %}
                {{forloop.counter}}
            {% endif %}
        </td>
        <td>{{products.name}}</td>
        <td>
            {% if request.user.is_superuser %}
                <div class="form-check form-switch">
                    <input 
                        class="form-check-input"
                        hx-post="{% url 'dashboard:product_category_status' products.id %}" 
                        hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'
                        type="checkbox" {% if products.status %} checked {% endif %}
                        style="cursor: pointer;"
                    >
                </div>  
            {% else %}
                {% if products.status %} Active {% else %} Inactive {% endif %}
            {% endif %}
        </td>
        <td>
            <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                {% if request.user.is_superuser %}
                    <a href="{% url 'dashboard:product_category_details' products.id %}" class="btn btn-success"><i class="bi bi-eye-fill"></i></a>
                {% endif %}
                {% if perms.authentication.edit_product_category %}
                    <button type="button" class="btn btn-info"
                        hx-get="{% url 'dashboard:update_product_category' products.id %}"
                        hx-target="#update-product-category-modal-content" 
                        data-bs-toggle="modal" data-bs-target="#update-product-category-modal"
                    ><i class="bi bi-pencil-square"></i></button>
                {% endif%}
                {% if perms.authentication.delete_product_category %}
                    <form action="{% url 'dashboard:delete_product_category' products.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this?')">  
                        {% csrf_token %}
                        <button type="submit" value="Delete" class="btn btn-sm btn-danger"><i class="bi bi-trash3-fill"></i></button>
                    </form>  
                {% endif %}
            </div>
        </td>
    </tr>
    {% endfor %}
{% else %}
    <td colspan="4" class="text-center"> No record found related to your search keyword</td>
{% endif %}