AssetManagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from authentication.forms import UserPasswordChangeForm, UserPasswordResetForm, UserPasswordResetRequestForm
from authentication.decorators import unauthenticated_user


urlpatterns = [
    path('secret/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('vendors/', include('vendors.urls', namespace='vendors')),
    path('products/', include('products.urls', namespace='products')),
    path('admin/', include('dashboard.urls', namespace='dashboard')),
    path('upload/', include('upload.urls', namespace='upload')),
    path('recycle-bin/', include('recycle_bin.urls', namespace='recycle_bin')),
    path('assets/', include('assets.urls', namespace='assets')),
    path('roles/', include('roles.urls', namespace='roles')),
    path('support/', include('support.urls', namespace='support')),
    path('users/', include('users.urls', namespace='users')),
    path('notifications/', include('notifications.urls', namespace='notifications')),

    # django smart select urls
    path('chaining/', include('smart_selects.urls')),

    # Password Change Views
    path('change-password/', auth_views.PasswordChangeView.as_view(form_class=UserPasswordChangeForm,
    	template_name='auth/password/password-change.html'), name='password_change'),

    path('change-password/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='auth/password/password-change-done.html'), name='password_change_done'),

    # Password Reset Views
    path('reset-password/', unauthenticated_user(auth_views.PasswordResetView.as_view(form_class=UserPasswordResetRequestForm,
        template_name='auth/password/password-reset.html', html_email_template_name='auth/verification/password_reset_html_email.html')), name="password_reset"),

    path('reset-password/done/', unauthenticated_user(auth_views.PasswordResetDoneView.as_view(
        template_name='auth/password/password-reset-done.html')), name="password_reset_done"),

    path('reset/<uidb64>/<token>', unauthenticated_user(auth_views.PasswordResetConfirmView.as_view(form_class=UserPasswordResetForm,
        template_name='auth/password/password-reset-confirm.html')), name="password_reset_confirm"),

    path('reset/done/', unauthenticated_user(auth_views.PasswordResetCompleteView.as_view(
        template_name='auth/password/password-reset-complete.html')), name="password_reset_complete"),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error Handlers
handler403 = 'error_handlers.views.handle_403'
handler404 = 'error_handlers.views.handle_404'
handler500 = 'error_handlers.views.handle_500'

recycle_bin/urls.py
from django.urls import path
from . import views

app_name = 'recycle_bin'

urlpatterns = [
    path('deleted-products', views.deleted_products, name='deleted_products'),
    path('deleted-products/restore/<uuid:id>', views.deleted_products_restore, name='deleted_products_restore'),
    path('deleted-products/delete/<uuid:id>', views.deleted_products_permanently, name='deleted_products_permanently'),
    path('deleted-products-search/<str:page>', views.deleted_products_search, name='deleted_products_search'),
    
    path('deleted-vendors', views.deleted_vendors, name='deleted_vendors'),
    path('deleted-vendors/restore/<uuid:id>', views.deleted_vendor_restore, name='deleted_vendor_restore'),
    path('deleted-vendors/delete/<uuid:id>', views.deleted_vendor_permanently, name='deleted_vendor_permanently'),
    path('deleted-vendors-search/<str:page>', views.deleted_vendors_search, name='deleted_vendors_search'),

    path('deleted-assets', views.deleted_assets, name='deleted_assets'),
    path('deleted-assets/restore/<uuid:id>', views.deleted_asset_restore, name='deleted_asset_restore'),
    path('deleted-assets/delete/<uuid:id>', views.deleted_asset_permanently, name='deleted_asset_permanently'),
    path('deleted-assets-search/<str:page>', views.deleted_assets_search, name='deleted_assets_search'),

    path('deleted-users', views.deleted_users, name='deleted_users'),
    path('deleted-users/restore/<uuid:id>', views.deleted_user_restore, name='deleted_user_restore'),
    path('deleted-users/delete/<uuid:id>', views.deleted_user_permanently, name='deleted_user_permanently'),
    path('deleted-users-search/<str:page>', views.deleted_users_search, name='deleted_users_search'),


    path('deleted-locations', views.deleted_locations, name='deleted_locations'),
    path('deleted-locations/restore/<uuid:id>', views.deleted_locations_restore, name='deleted_locations_restore'),
    path('deleted-locations/delete/<uuid:id>', views.deleted_locations_permanently, name='deleted_locations_permanently'),
    path('deleted-locations-search/<str:page>', views.deleted_locations_search, name='deleted_locations_search'),


    path('deleted-departments', views.deleted_depertments, name='deleted_departments'),
    path('deleted-departments/restore/<uuid:id>', views.deleted_departments_restore, name='deleted_departments_restore'),
    path('deleted-departments/delete/<uuid:id>', views.deleted_departments_permanently, name='deleted_departments_permanently'),
    path('deleted-departments-search/<str:page>', views.deleted_departments_search, name='deleted_departments_search'),


    path('deleted_product_categories', views.deleted_product_categories, name='deleted_product_categories'),
    path('deleted_product_categories/restore/<uuid:id>', views.deleted_product_categories_restore, name='deleted_product_categories_restore'),
    path('deleted_product_categories/delete/<uuid:id>', views.deleted_product_categories_permanently, name='deleted_product_categories_permanently'),
    path('search_deleted_product_categories/<str:page>', views.search_deleted_product_categories, name='search_deleted_product_categories'),

    path('deleted_product_types', views.deleted_product_types, name='deleted_product_types'),
    path('deleted_product_types/restore/<uuid:id>', views.deleted_product_types_restore, name='deleted_product_types_restore'),
    path('deleted_product_types/delete/<uuid:id>', views.deleted_product_types_permanently, name='deleted_product_types_permanently'),
    path('deleted_product_types_search/<str:page>', views.deleted_product_types_search, name='deleted_product_types_search'),

    path('deleted_asset_status', views.deleted_asset_status, name='deleted_asset_status'),
    path('deleted_asset_status/restore/<uuid:id>', views.deleted_asset_status_restore, name='deleted_asset_status_restore'),
    path('deleted_asset_status/delete/<uuid:id>', views.deleted_asset_status_permanently, name='deleted_asset_status_permanently'),
    path('deleted_asset_status_search/<str:page>', views.deleted_asset_status_search, name='deleted_asset_status_search'),
]

roles/urls.py
from django.urls import path
from .views import *

app_name = 'roles'

urlpatterns = [
    path('list', list, name='list'),
    path('add', add, name='add'),
    path('update/<str:name>', update, name='update'),
    path('delete/<str:name>', delete, name='delete'),
    path('status/<str:name>', status, name='status'),
    path('search/<str:page>', search, name='search'),
]

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('list', list, name='list'),
    path('detail/<uuid:id>', details, name='details'),
    path('add', add, name='add'),
    path('update/<uuid:id>', update, name='update'),
    path('delete/<uuid:id>', delete, name='delete'),
    path('status/<uuid:id>', status, name='status'),
    path('search/<str:page>', search, name='search'),
    path('csv', export_users_csv, name='export_users_csv'),
    path('pdf', export_users_pdf, name='export_users_pdf'),
    path('assigned-assets/<uuid:id>', user_assigned_assets, name='user_assigned_assets')
]

users/views.py
from django.shortcuts import render, redirect
from .forms import UserForm, UserUpdateForm, AddressForm
from django.contrib import messages
from django.http import HttpResponse
from django.core.paginator import Paginator
from authentication.models import User
from assets.models import AssignAsset
from dashboard.models import Address
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import Group
from .utils import create_all_perm_role
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from vendors.utils import render_to_csv, render_to_pdf
from django.db.models import Q
from django.contrib.auth.decorators import permission_required
from datetime import date
from assets.models import Asset,AssetImage
today = date.today()

PAGE_SIZE = 10
ORPHANS = 1


def check_admin(user):
    return user.is_superuser


def manage_access(user):
    permissions_list = [
        'authentication.view_users',
        'authentication.delete_users',
        'authentication.edit_users',
        'authentication.add_users',
    ]

    for permission in permissions_list:
        if user.has_perm(permission):
            return True

    return False


@login_required
@user_passes_test(manage_access)
def list(request):
    users_list = User.undeleted_objects.filter(organization=request.user.organization, is_superuser=False).exclude(
        pk=request.user.id).order_by('-created_at')
    deleted_user_count=User.deleted_objects.count()
    paginator = Paginator(users_list, PAGE_SIZE, orphans=ORPHANS)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    if request.method == "POST":
        messages.success(
            request, 'User added successfully and Verification email sent to the user')

        return redirect(request.META.get('HTTP_REFERER'))

    context = {'sidebar': 'users',
               'page_object': page_object, 'deleted_user_count':deleted_user_count,'title': 'Users'}
    return render(request, 'users/list.html', context=context)


@login_required
@permission_required('authentication.view_users')
def details(request, id):

    user = get_object_or_404(User.undeleted_objects, pk=id, organization=request.user.organization)
    assigned_assets = AssignAsset.objects.filter(user=user)
    
    
    
    history_list = User.history.all()
    paginator = Paginator(history_list, 10, orphans=1)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)

    asset_paginator=Paginator(assigned_assets,10,orphans=1)
    asset_page_number=request.GET.get('assets_page')
    asset_page_object=asset_paginator.get_page(asset_page_number)

    context = {
        'sidebar': 'users',
        'user': user,
        'page_object': page_object,
        'assigned_assets': asset_page_object,
        'title': 'User - Details'
    }
               
    return render(request, 'users/detail.html',context)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    # for get_asset in get_assigned_assets:
    #     get_obj['assigned_date']=get_asset['assigned_date']

    # for it in get_assigned_assets:
    #     get_asset_obj=Asset.objects.filter(id=it['asset_id'])
    #     for asset_data in get_asset_obj:
    #         get_obj['vendor']=asset_data.vendor.name if asset_data.vendor else 'N/A'
    #         get_obj['type']=asset_data.product.product_type.name if asset_data.product.product_type else 'N/A'

    #     get_asset=get_asset_obj.values()
    #     for it in get_asset:
    #         get_obj['asset_name']=it['name']
    #         get_obj['serial_no']=it['serial_no']
    #         get_obj['id']=it['id']

    #     assigned_assets.append(get_obj)

 


    


@login_required
@permission_required('authentication.add_users')
def add(request):
    form = UserForm(organization=request.user.organization)
    address_form = AddressForm()

    if request.method == "POST":
        create_all_perm_role()
        form = UserForm(request.POST, request.FILES,
        organization=request.user.organization)
        address_form = AddressForm(request.POST)

        if form.is_valid() and address_form.is_valid():
            user = form.save(commit=False)
            password1 = form.cleaned_data.get('password1', '')
            password2 = form.cleaned_data.get('password2', '')

            if password1 and password1 == password2:
                user.set_password(password1)
            address = address_form.save()
            user.organization = request.user.organization
            user.address = address
            user.save()
            # form.instance.role.user_set.add(form.instance)
            messages.success(
                request, 'User added successfully and Verification email sent to the user')

            all_perms, created = Group.objects.get_or_create(
                name='all_perms')

            if form.instance.access_level:
                all_perms.user_set.add(form.instance)
            else:
                all_perms.user_set.remove(form.instance)

            return HttpResponse(status=204)

    context = {
        'form': form,
        'address_form': address_form
    }

    return render(request, 'users/add-user-modal.html', context)


@login_required
@permission_required('authentication.edit_users')
def update(request, id):
    create_all_perm_role()
    user = get_object_or_404(
        User.undeleted_objects, pk=id, organization=request.user.organization)
    address = get_object_or_404(Address, pk=user.address.id)

    form = UserUpdateForm(
        instance=user, organization=request.user.organization)
    address_form = AddressForm(instance=address)
    old_email = user.email

    if request.method == "POST":
        form = UserUpdateForm(request.POST, request.FILES,
                              instance=user, organization=request.user.organization)
        address_form = AddressForm(request.POST, instance=address)

        if form.is_valid() and address_form.is_valid():
            form.instance.access_level
            form.instance.groups.clear()
            form.instance.role.user_set.add(form.instance)
            new_email = form.cleaned_data['email']
            if (old_email) != (new_email):
                messages.success(
                    request, 'User updated successfully and verification mail has been sent to the new email address')
            else:
                messages.success(request, 'User updated successfully')
            form.save()
            address_form.save()

            all_perms, created = Group.objects.get_or_create(
                name='all_perms')

            if form.instance.access_level:
                all_perms.user_set.add(form.instance)
            else:
                all_perms.user_set.remove(form.instance)

            return HttpResponse(status=204)

    context = {'user': user, 'form': form, 'address_form': address_form}
    return render(request, 'users/update-user-modal.html', context)


@login_required
@permission_required('authentication.delete_users')
def delete(request, id):
    if request.method == "POST":
        user = get_object_or_404(
            User.undeleted_objects, pk=id, organization=request.user.organization)

        if AssignAsset.objects.filter(user=user).exists():
            messages.error(
                request, 'Error! One or more Assets are assigned to this user')
        else:
            user.soft_delete()
            user.is_active = False
            user.save()
            messages.success(request, 'User deleted successfully')

    return redirect(request.META.get('HTTP_REFERER'))


@user_passes_test(check_admin)
def status(request, id):
    if request.method == "POST":
        user = get_object_or_404(
            User.undeleted_objects, pk=id, organization=request.user.organization)
        user.is_active = False if user.is_active else True
        user.save()

    return HttpResponse(status=204)


@login_required
def search(request, page):
    search_text = request.GET.get('search_text').strip()
    if search_text:
        return render(request, 'users/users-data.html', {
            'page_object': User.undeleted_objects.filter(Q(organization=request.user.organization) & Q(is_superuser=False) & (Q(
                username__icontains=search_text) | Q(full_name__icontains=search_text) | Q(phone__icontains=search_text) | Q(employee_id__icontains=search_text) | Q(department__name__icontains=search_text) | Q(role__related_name__icontains=search_text)
                | Q(location__office_name__icontains=search_text) | Q(address__address_line_one__icontains=search_text) | Q(address__address_line_two__icontains=search_text) | Q(address__country__icontains=search_text) | Q(address__state__icontains=search_text) | Q(address__pin_code__icontains=search_text) | Q(address__city__icontains=search_text)
            )).exclude(pk=request.user.id).order_by('-created_at')[:10]
        })

    user_list = User.undeleted_objects.filter(
        organization=request.user.organization, is_superuser=False).exclude(pk=request.user.id).order_by('-created_at')
    paginator = Paginator(user_list, PAGE_SIZE, orphans=ORPHANS)
    page_number = page
    page_object = paginator.get_page(page_number)
    return render(request, 'users/users-data.html', {'page_object': page_object})


@login_required
def export_users_csv(request):
    header_list = ['Name', 'Email', 'Phone', 'Designation', 'Department', 'Address Line One',
                   'Address Line Two', 'City', 'Pin Code', 'State', 'Country', 'Office']
    user_list = User.undeleted_objects.filter(organization=request.user.organization, is_superuser=False).exclude(pk=request.user.id).order_by('-created_at').values_list('full_name', 'email', 'phone', 'role__related_name',

templates/users/list.html
{% extends 'layouts/main-layout.html' %}
{% block content %}
{% load custom_filters %}

{% load static %}
<div class="page-heading">
    <div class="d-flex justify-content-between">
        <div class="page-title">
            <h3>Users</h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Users</li>
                </ol>
            </nav>
        </div>
        <div class="d-flex">
            {% if perms.authentication.add_users %}
                <div>
                    <button type="button" class="btn btn-sm btn-outline-info my-3 me-2" 
                        hx-get="{% url 'users:add' %}" hx-target="#add-user-modal-content"
                        data-bs-toggle="modal" data-bs-target="#add-user-modal">Add User
                    </button>
                </div>
            {% endif %}
            <a href="{% url 'recycle_bin:deleted_users' %}" class="btn btn-sm btn-outline-info my-3 trash-btn d-flex align-items-center position-relative">
                        <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-trash" style="margin-bottom: 2px;"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 7l16 0" /><path d="M10 11l0 6" /><path d="M14 11l0 6" /><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" /><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                        </svg>Trash</a>
        </div>
    </div>
    <section class="section">
        <!-- Add Modal -->
        <div class="modal fade text-left" id="add-user-modal" tabindex="-1" role="dialog"
            aria-labelledby="myModalLabel160" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div id="add-user-modal-content" class="modal-content" hx-target="this"></div>
            </div>
        </div>
        <!-- update modal -->
        <div class="modal fade text-left" id="update-user-modal" tabindex="-1" role="dialog"
            aria-labelledby="myModalLabel160" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div id="update-user-modal-content" class="modal-content" hx-target="this"></div>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                {% if page_object %}
                    <div class="d-flex justify-content-end my-2 gap-2">
                        <input name="search_text" type="search" class='dataTable-input' autocomplete="off" placeholder='Search here...'
                            hx-get="{% url 'users:search' page_object.number %}" hx-trigger="keyup changed delay:500ms, search" hx-target="#search_result">
                        {% if request.user.is_superuser %}
                            <button
                                type="button"
                                class="btn btn-secondary rounded"
                                data-bs-toggle="dropdown"
                                aria-haspopup="true"
                                aria-expanded="false"
                            ><i class="bi bi-download"></i></button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'users:export_users_csv' %}"><i class="bi bi-filetype-csv"></i> CSV Format</a>
                                <a class="dropdown-item" href="{% url 'users:export_users_pdf' %}"><i class="bi bi-filetype-pdf"></i> PDF Format</a>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
                <table class="table table-hover" id="table1">
                    <thead>
                        <tr>
                            <th>Sl No.</th>
                            <th>Image</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Assigned Assets</th>
                            <th>Designation</th>
                            <th>Access Level</th>
                            <th>Last Login</th>
                            {% if request.user.is_superuser %}
                                <th>Status</th>
                            {% endif %}
                            {% if perms.authentication.delete_users or perms.authentication.view_users or perms.authentication.edit_users %}
                                <th>Actions</th>
                            {% endif %}
                        </tr>
                    </thead>
                    {% if page_object %}
                    <tbody id="search_result">
                          {% for user in page_object %}
                        <tr>
                            <td>{{page_object.start_index|add:forloop.counter0}}</td>
                            <td>
                                <div class="user-img d-flex align-items-center">
                                    <div class="avatar avatar-lg">
                                        {% if user.profile_pic %}
                                            <img src="{{user.profile_pic.url}}">
                                        {% else %}
                                            <img src="{% static 'assets/images/faces/1.jpg' %}">
                                        {% endif %}
                                    </div>
                                </div>
                            </td>
                            <td>{{user.full_name | title}}</td>
                            <td>{{user.email}}</td>
                            <td>
                                <div style="display: flex; align-items: center; gap: 10px">
                                {% if user.id in user_asset_map_count %}
                                    <button type="button" 
                                            style="background: transparent; border: none; color: inherit; cursor: pointer;"
                                            hx-get="{% url 'users:user_assigned_assets' user.id %}" 
                                            class="open-product-modal btn p-0"
                                            hx-target="#show-user-asset-modal-content"
                                            data-bs-toggle="modal" 
                                            data-bs-target="#show-user-asset-modal">
                                        {{ user_asset_map_count|get_item:user.id }}
                                    </button>
                                    </div>
                                    <div class="modal fade text-left" id="show-user-asset-modal" tabindex="-1" role="dialog"
                                                aria-labelledby="myModalLabel140" aria-hidden="true">
                                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                                    <div id="show-user-asset-modal-content" class="modal-content" hx-target="this"></div>
                                                </div>
                                    </div>
                                </td>
                                {% endif %}
                                {% if user.id not in user_asset_map %}
                                    <p>0</p>
                                {% endif %}
                                </div>
                            </td>
                            <td>{{user.role}}</td>
                            <td>
                                {% if user.access_level %}
                                All
                                {% else %}
                                Only Assigned
                                {% endif %}
                            </td>
                            <td>{{user.last_login}}</td>
                            {% if request.user.is_superuser %}
                                <td>
                                    <div class="form-check form-switch">
                                        <input 
                                            class="form-check-input"
                                            hx-post="{% url 'users:status' user.id %}" 
                                            hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'
                                            type="checkbox" {% if user.is_active %} checked {% endif %}
                                            style="cursor: pointer;"
                                        >
                                    </div>
                                </td>
                            {% endif %}
                            <td>
                                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                    {% if perms.authentication.view_users %}
                                        <a href="{% url 'users:details' user.id %}" class="btn btn-success"><i class="bi bi-eye-fill"></i></a>
                                    {% endif %}
                                    {% if perms.authentication.edit_users %}
                                        <button type="button" class="btn btn-info" 
                                            hx-get="{% url 'users:update' user.id %}" hx-target="#update-user-modal-content"
                                            data-bs-toggle="modal" data-bs-target="#update-user-modal"
                                        ><i class="bi bi-pencil-square"></i></button>
                                    {% endif %}
                                    {% if perms.authentication.delete_users %}
                                        <form action="{% url 'users:delete' user.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this?')">  
                                            {% csrf_token %}
                                            <button type="submit" value="Delete" class="btn btn-sm btn-danger"><i class="bi bi-trash3-fill"></i></button>
                                        </form>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    {% else %}
                      <div class="alert alert-info" role="alert">
                           No record available!
                      </div>
                    {% endif %}
                </table>
                {% include 'commons/pagination.html' %}
            </div>
        </div>
    </section>
</div>
{% endblock content %}

templates/users/users-data.html
{% if page_object %}
{% load static %}
    {% for user in page_object %}
    <tr>
        <td>
            {% if page_object.start_index %}
                {{page_object.start_index|add:forloop.counter0}}
            {% else %}
                {{forloop.counter}}
            {% endif %}
        </td>
        <td>
            <div class="user-img d-flex align-items-center">
                <div class="avatar avatar-lg">
                    {% if user.profile_pic %}
                        <img src="{{user.profile_pic.url}}">
                    {% else %}
                        <img src="{% static 'assets/images/faces/1.jpg' %}">
                    {% endif %}
                </div>
            </div>
        </td>
        <td>{{user.full_name | title}}</td>
        <td>{{user.email}}</td>
        <td>{{user.role}}</td>
        <td>
            {% if user.access_level %}
            All
            {% else %}
            Only Assigned
            {% endif %}
        </td>
        <td>{{user.last_login}}</td>
        {% if request.user.is_superuser %}
            <td>
                <div class="form-check form-switch">
                    <input 
                        class="form-check-input"
                        hx-post="{% url 'users:status' user.id %}" 
                        hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}'
                        type="checkbox" {% if user.is_active %} checked {% endif %}
                        style="cursor: pointer;"
                    >
                </div>
            </td>
        {% endif %}
        <td>
            <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                {% if perms.authentication.view_users %}
                    <a href="{% url 'users:details' user.id %}" class="btn btn-success"><i class="bi bi-eye-fill"></i></a>
                {% endif %}
                {% if perms.authentication.edit_users %}
                    <button type="button" class="btn btn-info" 
                        hx-get="{% url 'users:update' user.id %}" hx-target="#update-user-modal-content"
                        data-bs-toggle="modal" data-bs-target="#update-user-modal"
                    ><i class="bi bi-pencil-square"></i></button>
                {% endif %}
                {% if perms.authentication.delete_users %}
                    <form action="{% url 'users:delete' user.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this?')">  
                        {% csrf_token %}
                        <button type="submit" value="Delete" class="btn btn-sm btn-danger"><i class="bi bi-trash3-fill"></i></button>
                    </form>
                {% endif %}
            </div>
        </td>
    </tr>
    {% endfor %}
{% else %}
    <td colspan="8" class="text-center"> No record found related to your search keyword</td>
{% endif %}